services:
  # A Docker web service
  - type: web
    name: Ngrok
    env: docker
    repo: https://github.com/craxid/rairu-kun # optional
    region: Singapore # optional (defaults to Singapore)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: PORT # ngrok port
        value: 22
      - key: 2rdebqSM07Pln2WRknYbSKERIxx_4aZW6A9SHXG2q3WbT9Tgq # ngrok token
        sync: false
      - key: REGION # ngrok region
        sync: false
